---
title: "Sinatra Testing ActiveRecord Validations and Associations"
type: "article"
behaviors:
  - sinatra
  - sinatra_activerecord
  - ruby_and_rspec
description: >
  Test AR Validations and Associations in Sinatra.  Simplify testing ActiveRecord associations using the shoulda library.
tags: "testing, shoulda, associations, activerecord, unit-testing, validations"
