source "https://rubygems.org"

gem 'activerecord', '~> 5.2'
gem 'pg', '~> 1.0'
gem 'rake'
gem "sinatra", "~> 2.0"
gem "sinatra-contrib"
gem 'sinatra-activerecord', '~> 2.0.13'
gem 'sinatra-flash'

group :test, :development do
  gem 'capybara'
  gem 'pry'
  gem 'rspec', '~> 3.7'
  gem 'database_cleaner'
  gem 'shoulda', '~> 3.5'
  gem 'shoulda-matchers', '~> 2.0'
  gem 'valid_attribute'
end
